// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcxXxz9hR_psJrBninr5mr8VSjcuYYX1I',
    appId: '1:536624780271:web:e4edeb6a319063d92d1c1a',
    messagingSenderId: '536624780271',
    projectId: 'cl-aafe5',
    authDomain: 'cl-aafe5.firebaseapp.com',
    storageBucket: 'cl-aafe5.firebasestorage.app',
    measurementId: 'G-LBGSNKWQF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsDm4OeRpc-iLKHyosZIUblkwMcYtyLzs',
    appId: '1:536624780271:android:d8b2cbdf726e71242d1c1a',
    messagingSenderId: '536624780271',
    projectId: 'cl-aafe5',
    storageBucket: 'cl-aafe5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsqOl0CoPvL7--VmBEikcBpqTYur8aolE',
    appId: '1:536624780271:ios:416b890ff570221c2d1c1a',
    messagingSenderId: '536624780271',
    projectId: 'cl-aafe5',
    storageBucket: 'cl-aafe5.firebasestorage.app',
    iosBundleId: 'com.example.youtube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsqOl0CoPvL7--VmBEikcBpqTYur8aolE',
    appId: '1:536624780271:ios:416b890ff570221c2d1c1a',
    messagingSenderId: '536624780271',
    projectId: 'cl-aafe5',
    storageBucket: 'cl-aafe5.firebasestorage.app',
    iosBundleId: 'com.example.youtube',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcxXxz9hR_psJrBninr5mr8VSjcuYYX1I',
    appId: '1:536624780271:web:9518b153575ee8c22d1c1a',
    messagingSenderId: '536624780271',
    projectId: 'cl-aafe5',
    authDomain: 'cl-aafe5.firebaseapp.com',
    storageBucket: 'cl-aafe5.firebasestorage.app',
    measurementId: 'G-YW14NM9DT6',
  );
}
